CREATE TABLE IF NOT EXISTS UserTags (
    Id INT NOT NULL AUTO_INCREMENT,
    UserId VARCHAR(255) NOT NULL,
    TagId INT NOT NULL,
    PRIMARY KEY(Id),
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (TagId) REFERENCES Tags(Id)
);
